[versions]
agp = "8.3.2"
kotlin = "1.9.22"
compose-compiler = "1.5.8"
room = "2.6.1"
lifecycle = "2.7.0"
ksp = "1.9.22-1.0.17"

[libraries]
# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Compose
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2024.02.01" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.8.2" }

# LiveData with Compose
androidx-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version = "1.6.0" }

# ViewModel with Compose
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

# Lifecycle
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

# Testing
junit = { module = "junit:junit", version = "4.13.2" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }